print("Hello, World!")
print("Hello, World!")
print("Hello, World!")
print("Hello, World!")
print("Hello, World!")
print("Hello, World!")
print("Hello, World!")
print("Hello, World!")
print("Hello, Rogomi!!")
print("Hello, Rogomi!!")
print("Hello, Rogomi :)!!")